### ISSUE TITLE
iotkit arduino not working

### ISSUE THREAD

**Issue by cyberneuron** [enableiot/iotkit-samples#26]
I've got all the settings done (referred to https://software.intel.com/en-us/node/530661 and https://github.com/enableiot/iotkit-samples/wiki), but something goes wrong with data transmission: 

both IoTKitSimpleExample and IoTKitActuationExample failed, 

in IoTKitSimpleExample, I do have temperature displayed on serial monitor, but no observation on https://dashboard.us.enableiot.com/ui/dashboard#/chart, 

in IoTKitActuationExample, no LED signal, and, no data displayed on serial monitor.
![image](https://cloud.githubusercontent.com/assets/7303077/6774086/cc852c2e-d155-11e4-9844-ffd6fc88bb25.png)

I've tried to modify `void begin(unsigned int localport = 41235);` into `void begin(unsigned int localport = 41234);` in file **IoTkit.h**, still, it doesn't work.
![image](https://cloud.githubusercontent.com/assets/7303077/6774136/cc160712-d156-11e4-95f6-3892387911ff.png)

`netstat -tulpn` in edison Yocto 1.6.1 shows:
![image](https://cloud.githubusercontent.com/assets/7303077/6774082/b410879c-d155-11e4-8daf-90f86a3b7058.png)

Have I missed something or there're some bugs in iotkit arduino?

Please help to tackle this issue.

Thanks.

**Comment by mtomczew** [comment]
Are you using newest version of iotkit-agent?
What is the output of iotkit-admin -V ?
If you updated, you should please restart iotkit-agent by running systemctl stop/status/start iotkit-agent

Check logs in /tmp/agent.log (default location) for errors when sending data to Cloud.

For actuations, you've chosen mqtt protocol on screenshot. Are you using that protocol (iotkit-admin protocol mqtt/rest+ws). Default protocol is websocket in configuration rest+ws. In application logs there should be information about successfull connection to mqtt / websocket server after iotkit-agent restart.

**Comment by bbaltz505** [comment]
Hi. Can you confirm that the iotkit-agent process is running? It listens to local data submissions on UDP port 41234. You should see some activity in /tmp/agent.log if it is running and you are submitting data.
Start the agent on the command-line with "systemctl start iotkit-agent".

**Comment by marcinma** [comment]
closing due missing information/activity, also some issues were fixed in new agent version.
