### ISSUE TITLE
Device already exists error

### ISSUE THREAD

**Issue by microspace** [enableiot/iotkit-samples#34]
Hello
I try to submit data to Intel IoT Cloud using this example
`iotkit-samples/api/javascript/examples/pull-example.js`
I get this error:
```
2016-01-29T21:32:56.517Z - debug: Account Guid: undefined
2016-01-29T21:32:57.868Z - error: UncaughtException: Device already exists
2016-01-29T21:32:57.873Z - error: undefined
```
Please, help me to solve this problem

**Comment by marcinma** [comment]
Hi,
as you can see in message, Device already exists, unfortunately your Device ID is unique in whole system, please make sure you are using unique deviceid (update config in /javascript/configs/app.json so it points to your account)

**Comment by microspace** [comment]
I changed Device ID in app.json. Now when I run `node pull-example.js` new device is created. 
Do I need to activate it? 
Can I semd data to device which was already activated with `iotkit-admin active KJHGjk` command?

**Comment by marcinma** [comment]
Yes, in order to submit data you have to activate device, if you already activated device and device token was properly saved on your machine you should be able to send data.

**Comment by microspace** [comment]
Problem is that new device is created each time I run `node pull-example.js`. This is strange and complicated for me. I give up.
